jobs:
- name: build-jekyll
  public: true
  plan:
  - get: repository
    trigger: true
  - get: gist
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/gh-pages}
      inputs: 
        - name: repository
        - name: gist
      outputs: 
        - name: site
      run:
        path: sh
        args:
        - -exc
        - |
           git clone gist site
           cd repository && jekyll build && cp _site/* ../site && cd ../site
           git config --global user.email "mig@jankjr.dk"
           git config --global user.name "jankjr" && git add .
           git commit -m "updated gist"
  - put: gist
    params: 
      repository: site


- name: test-site
  public: true
  plan: 
  - get: repository
    passed: [build-jekyll]
    trigger: true
  - task: curl-site
    config: 
      platform: linux
      image_resource: 
        type: docker-image
        source: 
          repository: praqma/gh-pages
      run: 
        path: sh
        args: 
        - -exc
        - |
          apt-get update
          apt-get install -y curl
          curl https://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
  - task: link-checker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/linkchecker}
      run:
        path: sh
        args:
        - -exc
        - |
          linkchecker http://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
- name: update-production-site
  public: true
  plan:
  - get: repository
    passed: [test-site]
  - put: github-pages
    params:
      repository: repository
      force: true
  
resources: 
- name: repository
  type: git
  source:
    uri: https://github.com/jankjr/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: gist
  type: git 
  source: 
    uri: https://gist.github.com/4b2015849c31bfb860c6a021ba9ed63a.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: github-pages
  type: git
  source: 
    uri: https://github.com/jankjr/concourse-workshop.git
    branch: gh-pages
    username: {{github-username}}
    password: {{github-password}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
